#! /usr/bin/env python

from ogreclient.cli import entrypoint


def main():
    '''
    The main entry point for ogreclient CLI
    '''
    entrypoint()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit('\nExiting gracefully on Ctrl-c')
