#! /bin/bash

#####
# Tell git to use hooks directory with:
#   git config core.hooksPath hooks/*
##

# stash everything except what's staged
git stash -q --keep-index

# return the working tree to its previous state on exit
trap 'git stash pop -q' EXIT

# move to repo root
cd "$(git rev-parse --show-toplevel)"

# determine if JS is being modified
if ! git diff-index --exit-code HEAD ogreserver/static/js; then
	# compile using Google's Closure Compiler webservice
  ERRORS=$(closure-compiler -o errors --language=ecma6 ogreserver/static/js/*)

	# store return code from validation
	RET=$?

	# print any errors reported
	if [[ $RET -ne 0 ]]; then
		echo "$ERRORS"
		exit $RET
	fi
fi

# exit with the return code validation
exit $RET
