#! /bin/bash -e
#
# Ogreclient install script for OSX and linux
#

OGRE_HOST=${OGRE_HOST:-https://ogre-staging.oii.yt}

trap "echo Exited!; exit;" SIGINT SIGTERM

RED=$(tput setaf 1; tput bold)
GREEN=$(tput setaf 2; tput bold)
BLUE=$(tput setaf 4; tput bold)
RESET=$(tput sgr0)

function install_homebrew {
  if ! command -v brew >/dev/null 2>&1; then
    echo "${BLUE}==> Installing Homebrew${RESET}"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

if [[ $(uname) =~ (.*)Darwin(.*) ]]; then
  install_homebrew

  if ! command ebook-meta &>/dev/null; then
    echo "${BLUE}==> Installing Calibre${RESET}"
    brew cask install calibre
  fi

  # install OGRE directly into /usr/local/bin
  echo "${BLUE}==> Installing OGRE from ${OGRE_HOST}:${RESET}"
  curl -q -o /usr/local/bin/ogre -L -k "$OGRE_HOST/download/ogreclient"
  sudo chmod +x /usr/local/bin/ogre

  if [[ -z $(system_profiler SPApplicationsDataType | awk '/Kindle.app/ {print $2}') ]]; then
    echo "${BLUE}==> Kindle for Mac is missing:${RESET}"
    brew cask install kindle
  fi

  if ! ls /Applications/BitBar* >/dev/null 2>&1; then
    echo "${BLUE}==> Installing BitBar for Mac:${RESET}"
    cd /tmp
    curl -o BitBarDistro.zip -L -k "$OGRE_HOST/download/bitbar"
    unzip -q -o BitBarDistro.zip
    rsync -a /tmp/BitBarDistro.app/ /Applications/BitBarDistro.app
    rm -rf BitBarDistro.zip BitBarDistro.app
  fi

  echo "${GREEN}==> OGRE install complete${RESET}"
  echo ''

  # open Kindle for Mac on first run
  if [[ ! -d ~/.config/ogre ]]; then
    open --background /Applications/Kindle.app
  fi

elif [[ $(uname) =~ (.*)Debian(.*) ]]; then
  echo "${RED}Not implemented for Debian${RESET}"
  exit 1

elif [[ $(uname) =~ (.*)Ubuntu(.*) ]]; then
  echo "${RED}Not implemented for Ubuntu${RESET}"
  exit 1

fi
