#! /bin/bash -e
#
# Ogreclient install script for OSX and linux
#

OGRE_HOST=${OGRE_HOST:-https://ogre-staging.oii.yt}

trap "echo Exited!; exit;" SIGINT SIGTERM

RED=$(tput setaf 1; tput bold)
GREEN=$(tput setaf 2; tput bold)
BLUE=$(tput setaf 4; tput bold)
RESET=$(tput sgr0)
DEBUG=1

function debug {
  if [[ $DEBUG -eq 1 ]]; then
    echo "${RED}$1: $2${RESET}"
  fi
}

function install_homebrew {
  if ! command -v brew >/dev/null 2>&1; then
    echo "${BLUE}==> Installing Homebrew${RESET}"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

function install_kindle_osx {
  echo "${BLUE}==> Installing Kindle for Mac${RESET}"
  curl -q -o /tmp/kindle.dmg -L https://s3.amazonaws.com/kindleformac/44182/KindleForMac-44182.dmg
  debug 'DOWNLOAD' "$(ls -l /tmp/kindle.dmg)"
  VOLUME=$(hdiutil mount /tmp/kindle.dmg | awk '/disk1(.*)Apple_HFS/ {print $3}')
  debug 'VOLUME' "$VOLUME"
  cp -R "$VOLUME/Kindle.app" /Applications
  debug 'APP' "$(file /Applications/Kindle.app)"
  umount "$VOLUME"
}

function version {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
}


if [[ $(uname) =~ (.*)Darwin(.*) ]]; then
  install_homebrew

  if ! command ebook-meta &>/dev/null; then
    echo "${BLUE}==> Installing Calibre${RESET}"
    brew cask install calibre
  fi

  # install OGRE directly into /usr/local/bin
  echo "${BLUE}==> Installing OGRE from ${OGRE_HOST}:${RESET}"
  curl -q -o /usr/local/bin/ogre -L -k "$OGRE_HOST/download/ogreclient"
  sudo chmod +x /usr/local/bin/ogre

  # find Kindle for Mac
  KINDLE_APP="$(system_profiler SPApplicationsDataType | awk '/Kindle.app/ {print $2}')"

  debug 'KINDLE APP' "${KINDLE_APP}"

  if [[ -z $KINDLE_APP ]]; then
    # kindle is missing
    install_kindle_osx

  else
    # determine kindle version
    KINDLE_VERSION="$(plutil -p "$KINDLE_APP/Contents/Info.plist" | awk '/CFBundleShortVersionString/ {print substr($3, 2, length($3)-2)}')"

    echo "==> Kindle version $KINDLE_VERSION found"

    if [[ $(version "$KINDLE_VERSION") -ge $(version "1.17.1") ]]; then
      # reinstall lower Kindle version
      echo "${BLUE}==> Version 1.17.1 or lower required.. Reinstalling${RESET}"
      sudo rm -rf "$KINDLE_APP"
      install_kindle_osx
    fi
  fi

  if ! ls /Applications/BitBar* >/dev/null 2>&1; then
    echo "${BLUE}==> Installing BitBar for Mac:${RESET}"
    cd /tmp
    curl -o BitBarDistro.zip -L -k "$OGRE_HOST/download/bitbar"
    unzip -q -o BitBarDistro.zip
    rsync -a /tmp/BitBarDistro.app/ /Applications/BitBarDistro.app
    rm -rf BitBarDistro.zip BitBarDistro.app
  fi

  echo "${GREEN}==> OGRE install complete${RESET}"
  echo ''

  # open Kindle for Mac on first run
  if [[ ! -d ~/.config/ogre ]]; then
    open --background /Applications/Kindle.app
  fi

elif [[ $(uname) =~ (.*)Debian(.*) ]]; then
  echo "${RED}Not implemented for Debian${RESET}"
  exit 1

elif [[ $(uname) =~ (.*)Ubuntu(.*) ]]; then
  echo "${RED}Not implemented for Ubuntu${RESET}"
  exit 1

fi
